#!/usr/bin/env bash

cd "$HOME"

# install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo ">>> Installing homebrew.."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

if [ -f "$HOME/.Brewfile" ]; then
  echo ">>> Installing brew packages.."
  brew bundle --global
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  echo ">>> Installing tmux tpm"
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm 
fi 


if [ ! -f "/usr/local/bin/starship" ]; then
  echo "Installing starship (shell prompt)"
  sudo curl -fsSL https://starship.rs/install.sh | bash
fi

if [ ! -f "$HOME/.config/omf/.yadm-installed" ]; then
  echo ">>> Installing Oh My Fish.."
  curl -L https://get.oh-my.fish | fish
  touch $HOME/.config/omf/.yadm-installed
fi

if [ ! -f "$HOME/.config/nvim/autoload/plug.vim" ]; then
  echo ">>> Installing plug.vim for nvim"
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
fi

if [ $SHELL != "/usr/local/bin/fish" ]; then
  echo "/usr/local/bin/fish"|  sudo tee -a /etc/shells
  echo "Setting default shell to fish"
  chsh -s /usr/local/bin/fish
fi

if [ ! -f "$HOME/.config/yadm/bootstrap.d/asdf-installs.sh" ]; then
  echo ">>> Installing additional tools using asdf..." 
  $HOME/.config/yadm/bootstrap.d/asdf-installs.sh
fi

echo ">>> Enabling font smoothing for retina displays"
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
defaults -currentHost write -globalDomain AppleFontSmoothing -int 2
