alias k='kubectl'
alias ns='kubie ns'
alias ctx='kubie ctx'
alias r='rails'
alias kg='kubectl get'
alias be='bundle exec'
alias ber='bundle exec rails'
alias tctl='docker exec temporal-admin-tools tctl'
